version: "3.7"
   
services:
  database:
    image: "postgres"
    ports:
      - 5432:5432
    env_file:
      - db.env
    volumes:
      - database-data:/var/lib/postgresql/data/

  server:
    build: server
    command: python server.py
    volumes:
      - ./server/src:/code
    ports:
      - 5000:5000
    env_file:
      - server/.env


volumes:
  database-data:


x-disabled:

